PRO_JOKES_EN = [
    "Don't use \"beef stew\" as a computer password. It's not stroganoff",
    "How does a computer get drunk? It takes screenshots...",
    "There are 10 types of people in the world: those who understand binary, and those who don’t.",
    "An SQL statement walks into a bar and sees two tables. It approaches, and asks “may I join you?”",
    "Why is it that programmers always confuse Halloween with Christmas? Because 31 OCT = 25 DEC.",
    "Two strings walk into a bar and sit down. The bartender says, \"So what’ll it be?\n" +
    "The first string says, \"I think I’ll have a beer quag fulk boorg jdk^CjfdLk jk3s d#f67howe%^U r89nvy~~owmc63^Dz x.xvcu\" \n" +
    "\"Please excuse my friend,\" the second string says. \"He isn’t null-terminated.\" \n",
    "A programmer’s wife tells him, \"While you’re at the grocery store, buy some eggs.\" He never comes back.",
    "What is the biggest lie in the entire universe? \"I have read and agree to the Terms and Conditions.\"",
    "Why was the JavaScript developer sad? Because he didn't Node how to Express himself",
    "In order to understand recursion you must first understand recursion.",
    "Why do Java developers wear glasses? Because they can't C#",
    "What do you call 8 hobbits? A hobbyte",
    "Why did the geek add body { padding-top: 1000px; } to his Facebook profile? He wanted to keep a low profile.",
    "An SEO expert walks into a bar, bars, pub, tavern, public house, Irish pub, drinks, beer, alcohol",
    "8 bytes walk into a bar, the bartenders asks \"What will it be?\" One of them says, \"Make us a double.\"",
    "Two bytes meet. The first byte asks, \"Are you ill?\" The second byte replies, \"No, just feeling a bit off.\"",
    "\"Knock, knock. Who's there?\" very long pause... \"Java.\"",
    "There's a band called 1023MB. They haven't had any gigs yet.",
    "A programmer's wife asks him to pick up some groceries on his way home from work. He asks what she needs, and she says to pick up a gallon of milk, and if they have eggs, get a dozen. When he returns home, his wife asks why he brought home 12 gallons of milk, and he responded that they did indeed have eggs.",
    "I was dressed up as a UDP packet for the Halloween. I don’t think anyone got it, but I couldn’t tell.",
    "How did you like my HTTP 200 joke? It was Ok.",
    "I ran out of new IPv4 jokes. I could tell you an IPv6 one but I'm afraid, you might not understand it.",
    "A forged DNS packet walked into a bar and asks the bartender: \"Need a root?\" The next day, no one can find the bar…",
    "The worst thing about a broadcast joke is that you have to tell it to everyone in order to find the one person who gets it.",
    "How many programmers does it take to change a light bulb? None – It’s a hardware problem",
    "What's the best think about Booleans? Even if you are wrong, you are only off by a bit"
]

JOKES_EN = [
    "Want to hear a construction joke? Oh never mind, I'm still working on that one.",
    "Two artists had an art contest. It ended in a draw!",
    "Have you ever tried eating a clock? It's really time-consuming",
    "Why are ghosts such bad liars? Because they are easy to see through.",
    "What did the buffalo say when his son left for college? Bison!",
    "Where do fish sleep? In the riverbed.",
    "What do you call a dinosaur that is sleeping? A dino-snore!",
    "Two pickles fell out of a jar onto the floor. What did one say to the other? Dill with it.",
    "Why was 6 afraid of 7? Because 7, 8, 9",
    "What's the best thing about Switzerland? I don't know, but their flag is a huge plus.",
    "Never criticize someone until you have walked a mile in their shoes. That way, when you criticize them, you'll be a mile away, and you'll have their shoes.",
    "What did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing.",
    "I used to be addicted to soap. But I'm clean now.",
    "What do you call bears with no ears? B–",
    "Two windmills are standing in a wind farm. One asks, \"What's your favorite kind of music?\" The other says, \"I'm a big metal fan.\"",
    "What do you call a bee that can't make up its mind? A maybe.",
    "What do you call the wife of a hippie? A Mississippi.",
]
